 # config.yaml
path: "C:\Users\011\PycharmProjects\pythonProject3\dataset" # Путь к папке с вашим датасетом
train: "C:\Users\011\PycharmProjects\pythonProject3\dataset\images" # Путь к папке с тренировочными изображениями
val: "C:\Users\011\PycharmProjects\pythonProject3\dataset\images" # Путь к папке с валидационными изображениями
nc: 2 # Укажите количество классов в вашем датасете
names: ['roki-2', 'walker'] # Список с названиями классов